### ISSUE TITLE
An inference problem

### ISSUE THREAD

**Issue by JesseZZZZZ** [uzh-rpg/rampvo#5]
Hi, dear authors.
I am now implementing RampVO on my own server, the installation has been successful and the evaluation process is done without errors. However, **the ate is 1000 for all scenes in TartanairEvent**... I used the RampVO_MultiScale.pth, following the instruction you provided in readme. Is the pth file somehow corrupted? It seems like the .pth file is wrong or something, because for all validation scenes, the ate is 1000.
Looking forward to your reply~

**Comment by senecobis** [comment]
Hi @JesseZZZZZ the reason why you are getting 1000 is for the evaluation code at this [line](https://github.com/uzh-rpg/rampvo/blob/0198aafc8dc014773770fd5f19c355c3c826ea77/evaluate.py#L286). Essentially the alignment between your estimated trajectory and the GT trajectory is wrong, and this is causing an exception.
This is can be caused by incorrectly placing the data or the perhaps using the wrong extension for images (we used .png).
Unfortunately without additional details I cannot give you a final response.

For TartanEvent, the order of error should be between 10^-1 and 10^-2 and probably the .pth is not corrupted, otherwise you wouldn't be able to run the code at all.

**Comment by JesseZZZZZ** [comment]
@senecobis Thank you for your answer! I was being stupid and now I've fixed the problem~
